/**
 * Inventory loading + tag/signal scoring + explanation templating.
 *
 * Deliberately NOT a live Claude call per recommended vehicle: the source
 * spec's "short explanation generated by AI" is satisfied here by filling a
 * template from the actual matched signal/tag evidence Claude (or the local
 * regex fallback) already extracted — not a second LLM round-trip. That
 * keeps this engine fast, offline-capable, and deterministic, which the spec
 * asks for explicitly and which a second live call per vehicle would break.
 */

let _inventory = null;
let _loadPromise = null;

export async function loadInventory() {
  if (_inventory) return _inventory;
  if (!_loadPromise) {
    _loadPromise = fetch('./inventory.json')
      .then(r => { if (!r.ok) throw new Error(`inventory.json HTTP ${r.status}`); return r.json(); })
      .then(data => { _inventory = data; return data; })
      .catch(err => { _loadPromise = null; throw err; }); // allow retry on next call if it failed
  }
  return _loadPromise;
}

// Only signal types with a clear vehicle-attribute correlate are mapped —
// trade_in/purchase_ready/insurance say something about the CONVERSATION
// (a trade-in is happening, the customer is close to deciding, insurance
// came up) but nothing about which vehicle TYPE fits, so they're
// deliberately left unmapped rather than forced onto an arbitrary tag.
const SIGNAL_TO_TAG = {
  financing: 'financing',
  family: 'family',
  price_sensitivity: 'budget',
};

const SIGNAL_LABEL_FI = {
  financing: 'rahoituskiinnostus',
  family: 'perhetarve',
  price_sensitivity: 'hintaherkkyys',
};

const AVAILABILITY_BONUS = { available: 0.3, reserved: 0.1, incoming: 0 };

// Lists ALL matched signal types, not just the first/strongest one — a
// vehicle matching on both financing and family tags gets a two-part
// explanation ("rahoituskiinnostus, perhetarve"), not a single arbitrarily
// chosen reason. matchedSignalTypes is already in a consistent order across
// every vehicle in one scoring pass (it's filtered from the same
// presentTypes array — see scoreVehicles), so the explanation text is
// deterministic per signal set, not per vehicle.
function buildExplanation(matchedSignalTypes) {
  const labels = matchedSignalTypes.map(t => SIGNAL_LABEL_FI[t]).filter(Boolean);
  if (!labels.length) return 'Yleinen suositus.';
  return `Suositeltu, koska keskustelussa nousi esiin: ${labels.join(', ')}.`;
}

/**
 * Pure function: (inventory, signals) -> top matches with matchScore (0-100)
 * and a template-filled explanation. No network, no randomness — same
 * inputs always produce the same output.
 */
export function scoreVehicles(inventory, signals, count = 3) {
  const presentTypes = [...new Set(signals.map(s => s.type))].filter(t => SIGNAL_TO_TAG[t]);
  if (!presentTypes.length) return [];

  const presentTags = [...new Set(presentTypes.map(t => SIGNAL_TO_TAG[t]))];

  const scored = inventory
    .map(v => {
      const matchedTags = presentTags.filter(tag => v.tags.includes(tag));
      if (!matchedTags.length) return null;
      const matchedSignalTypes = presentTypes.filter(t => matchedTags.includes(SIGNAL_TO_TAG[t]));
      const rawScore = matchedTags.length + (AVAILABILITY_BONUS[v.available] || 0);
      const matchScore = Math.round((matchedTags.length / presentTags.length) * 100);
      return { vehicle: v, rawScore, matchScore, matchedSignalTypes };
    })
    .filter(Boolean);

  // Tie-break order, explicit rather than relying on sort stability:
  // 1. rawScore (matched-tag count + availability bonus) — the real signal.
  // 2. price ascending — CONFIRMED business decision with the product owner
  //    (not a default-by-omission): cheapest-equally-relevant-match wins,
  //    over "most expensive first" (margin/premium framing) or "newest
  //    year first" (lower perceived risk). Chosen to minimize price-
  //    objection risk, consistent with this app's own "hinta" scenario
  //    philosophy of addressing price concerns proactively. (No structured
  //    budget figure is extracted from the transcript today, so "closest to
  //    the customer's stated budget" isn't available as a tiebreaker — that
  //    would need numeric budget extraction added to signals.js first.)
  // 3. vehicle id — final deterministic fallback so the exact same signal
  //    set always produces the exact same top-3, never order-of-insertion
  //    dependent.
  scored.sort((a, b) =>
    b.rawScore - a.rawScore ||
    a.vehicle.price - b.vehicle.price ||
    a.vehicle.id.localeCompare(b.vehicle.id)
  );

  return scored.slice(0, count).map(x => ({
    ...x.vehicle,
    matchScore: x.matchScore,
    explanation: buildExplanation(x.matchedSignalTypes),
  }));
}

export async function getTopMatches(signals, count = 3) {
  if (!signals.length) return [];
  const inventory = await loadInventory();
  return scoreVehicles(inventory, signals, count);
}

/**
 * Distinguishes "no signals detected yet" from "signals were detected, but
 * none of them say anything about vehicle preference" (e.g. purchase_ready,
 * trade_in, insurance — process-stage signals, not vehicle-attribute
 * signals). Returns the distinct signal labels responsible when the latter
 * applies, or null otherwise — the UI uses this to show an explained empty
 * state instead of a bare placeholder that reads as broken/pending forever.
 */
export function unmatchedSignalLabels(signals) {
  if (!signals || !signals.length) return null;
  const hasVehicleRelevantSignal = signals.some(s => SIGNAL_TO_TAG[s.type]);
  if (hasVehicleRelevantSignal) return null;
  return [...new Set(signals.map(s => s.label))];
}
